logging:
  level:
    org.springframework: DEBUG

springdoc:
  api-docs:
    path: /apispecs/api-specs.yaml
  swagger-ui:
    path: /api/swagger-ui.html


management:
  endpoints:
    web:
      exposure:
        include: "*"
